CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30),
    surname VARCHAR(30),
    age INT,
    gender VARCHAR(30),
    phone VARCHAR(30),
    telegram_login VARCHAR(30),
    register_date DATE
);