CREATE TABLE schedule (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    activity_id INT,
    coach_id INT,
    start_time DATE,
    end_time DATE,
        FOREIGN KEY (activity_id) REFERENCES activity(id),
        FOREIGN KEY (coach_id) REFERENCES users(id)
);